## 빅데이터 주요모듈 학습

### Numpy

In [1]:
# numpy 설치
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

np.__version__

'1.26.4'

In [3]:
lst = [1, 2, 3, 4, 5]
vec = np.array(lst)
vec

array([1, 2, 3, 4, 5])

In [4]:
vec = np.array([1,3,5,7,9])
vec

array([1, 3, 5, 7, 9])

In [5]:
# 현재 vec의 형태 확인
# 1차원 배열(크기, )
vec.shape

(5,)

In [7]:
# 파이썬에서 2차원 리스트는 가변이 가능
lst2 = [[1,2,3],[4,5,6,7]]
lst2

[[1, 2, 3], [4, 5, 6, 7]]

In [15]:
# 2차원 배열
mat = np.array([[1,2,3], [4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# 2차원 배열 - (행, 열)
mat.shape

(2, 3)

In [17]:
print(type(lst), type(vec))
print(type(lst2), type(mat))

<class 'list'> <class 'numpy.ndarray'>
<class 'list'> <class 'numpy.ndarray'>


In [18]:
# 배열초기화
mat_one = np.ones((2,3))
mat_one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
mat_zero = np.zeros((2,3))
mat_zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
mat_unit = np.eye(3)
mat_unit

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 랜덤행렬
mat_rand = np.random.random((2,3))
mat_rand

array([[0.69766321, 0.72749001, 0.63231539],
       [0.02139476, 0.37315236, 0.27429326]])

In [29]:
# 0 ~ 9 까지 초기화 배열
vec_rng = np.arange(10)
vec_rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- 행렬연산에 +, -, *, / 연산가능
- np.add(), np.subtract(), np.muliply(), np.divide() 로도 사용가능

#### Pandas

- 손쉬운 데이터처리를 위한 라이브러리. 데이터분석시 필수 라이브러리

##### 설치

```shell
> pip install pandas
```

In [30]:
# pandas 설치
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [31]:
import pandas as pd

pd.__version__

'2.2.3'

#### 데이터 구조
- DataFrame : 2차원 배열과 동일(기본타입)
- Series : 1차원 배열과 동일(단위타입)

<img src="../image/ml0003.png" width="600">

In [32]:
# 데이터프레임 생성
# 파이썬 리스트, 딕셔너리, 튜플에서 변환 가능
datas = {
    '이름' : ['길동이', '길순이', '유고', '애슐리'],
    '국어' : [81.2, 100.0, 10.0, 90.3],
    '영어' : [54.4, 100.0, 99.5, 100.0]
}

df1 = pd.DataFrame(datas)

In [33]:
df1

이름     국어     영어
0  길동이   81.2   54.4
1  길순이  100.0  100.0
2   유고   10.0   99.5
3  애슐리   90.3  100.0

In [34]:
# 시리즈 생성
score = pd.Series(data=['길동이', 81.2, 54.4], index = ['이름', '국어', '영어'])
score

이름     길동이
국어    81.2
영어    54.4
dtype: object

In [35]:
# 엑셀, CSV 로드 - 이 형태로 데이터프레임 생성 가장 빈도높음
df2 = pd.read_csv('./student_score.csv', encoding='utf-8')
df2

student_id   name  score
0        2001  Steve   89.9
1        2002   Bill   99.8
2        2003  Ellon  100.0
3        2004  Ellen   67.5
4        2005   Tony   90.3